### PR TITLE
Use lpsum instead of plain addition for constraints

### LINKED ISSUE #56: Use lpsum function in place of plain addition
Similar to #55 the `lpsum` function could be used in place of plain addition for the the remaining constraint functions and also the optimisation functions

### PR DESCRIPTION
**Pull request by meatballs**
Fixes #56

### CODE REVIEW

**Comment by meatballs** [comment]
Whoops. I committed a change to `setup.cfg` that I've been testing on this branch by accident.

**Comment by drvinceknight** [comment]
I've been down the road of getting pytest as a runner for the doctests: https://github.com/PyconUK/ConferenceScheduler/pull/28

I came to the conclusion that it wasn't the way to go:

- I could tell travis specifically (not appveyor) to run them so that made appveyor happy (it looks like the order is OS dependent)
- That doesn't work because travis doesn't get failures as a failed signal.

**Comment by meatballs** [comment]
Pretty much the conclusion I'm coming too - just didn't intend to do it on this branch!

**Comment by meatballs** [comment]
Oh good grief, it failed to commit the reversal!!! Agggghhhh......

**Comment by meatballs** [comment]
coveralls.io is playing up. It's showing that there's no change in coverage at https://coveralls.io/builds/11432442 but not reporting it here

**Comment by drvinceknight** [comment]
Yeah I've been waiting on it. This looks good to me, feel free to merge :+1:

**Pull request merged**
