### PR TITLE
Use properties for event.tags and event.unavailability

### LINKED ISSUE #76: Event Methods
We have created an Event class - largely because we realised that an Event's state needs to change after it has been initialised (its unavailability). However, we are still manipulating its `unavailability` attribute directly within our code.

I suggest that, instead, we should create getter/setter methods to provide some isolation. My initial thoughts are something like the following:

```
def set_unavailable_for_slot(self, slot):
    """Sets the event to be unavailable for the given slot"""

def set_unavailable_at(self, unavailable_from, unavailable_until):
    """Sets the event to be unavailable for a period of time"""

def set_to_avoid(self, event):
    """Sets the event's unavailability so as to avoid a clash with the given event"""

def is_unavailable_for(self, slot):
    """A boolean returning true if the event is unavailable for the given slot, false otherwise"""
```

### PR DESCRIPTION
**Pull request by meatballs**
Fixes #76

### CODE REVIEW

**Comment by drvinceknight** [comment]
Are you happy there's nothing weird going on with the chair schedule being changed in the tutorial? I'm pretty sure it's just the different order of constraints but worth making sure we're sure.

**Comment by drvinceknight** [comment]
(Possibly as a second issue/PR we should have a short how to going over "manipulating event unavailability and tags" just briefly showing the other two methods.)

**Comment by meatballs** [comment]
> Are you happy there's nothing weird going on with the chair schedule being changed in the tutorial? I'm pretty sure it's just the different order of constraints but worth making sure we're sure.

I agree it's probably nothing but I'd like to go through that and make sure I'm happy it's still a valid solution. I've not done that yet.

**Comment by meatballs** [comment]
Found a bug...

**Comment by drvinceknight** [comment]
This looks good to me. Not sure what order you prefer this to go in re #75 so will leave merging to you. :+1:

**Comment by meatballs** [comment]
OK. I'm just looking at cleaning up one of those dicts a little....

**Comment by meatballs** [comment]
Let's get #75 finished first and then I can just alter the one line in here to fix it

**Pull request merged**
