### PR TITLE
Use integers instead of floats for arrays returned from scheduler.array

### LINKED ISSUE #91: Use integers rather than floats in array format
The `scheduler.array` function and the conversions to array format are producing arrays of floats. We should change this to be integers.

### PR DESCRIPTION
**Pull request by alexwlchan**
Resolves #91.

### CODE REVIEW

**Comment by meatballs** [comment]
We seem to have a problem on appveyor here. Not sure why....

**Comment by drvinceknight** [comment]
> We seem to have a problem on appveyor here. Not sure why....

Is this perhaps a clue? http://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine

**Comment by alexwlchan** [comment]
At a total guess, numpy is picking a slightly different int type on Windows?

**Comment by drvinceknight** [comment]
Would setting the type to be `np.int64` work? (I am stabbing in the dark here)

**Comment by alexwlchan** [comment]
> Would setting the type to be `np.int64` work?

Yeah, it was probably a mistake of me to be inconsistent in the first place.

**Comment by drvinceknight** [comment]
> . Let's give it a go!

Appveyor seems happy! :+1:

**Comment by meatballs** [comment]
using `int64` for these seems a little OTT. They will only ever be 0 or 1, so I'd have thought `bool` would be more appropriate.

**Comment by alexwlchan** [comment]
> using int64 for these seems a little OTT. They will only ever be 0 or 1, so I'd have thought bool would be more appropriate.

I will freely admit I’m not a numpy expert. If you use `np.bool`, it looks like you're getting `True` or `False` out. Maybe `np.int8`?

**Comment by meatballs** [comment]
I believe that in Python 3, `True` and `False` are keywords and will be always be equal to 1 and 0. In  Python 2 it was different, but we should be with `bool` here.

**Comment by drvinceknight** [comment]
We don't want the array str to actually have `True` `False` in it thought right? We want 0 and 1.

**Comment by drvinceknight** [comment]
> We want 0 and 1.

For completeness:

```python
>>> import numpy as np
>>> a = np.zeros((3, 3), dtype=np.bool)
>>> a[0, 1] = 1
>>> a[2, 1] = 1
>>> a
array([[False,  True, False],
       [False, False, False],
       [False,  True, False]], dtype=bool)
>>> b = np.zeros((3, 3), dtype=np.int8)
>>> b[0, 1] = 1
>>> b[2, 1] = 1
>>> b
array([[0, 1, 0],
       [0, 0, 0],
       [0, 1, 0]], dtype=int8)
```

My preference would be `np.int8`.

**Comment by meatballs** [comment]
Ah well. Bool would have been nice but we really do need to see actual integers! Int8 for me too.

**Comment by drvinceknight** [comment]
Simple doctest failure in `mathematical-model.rst`:

```
029     >>> array = scheduler.schedule_to_array(schedule, events=events, slots=slots)
030     >>> array
Expected:
    array([[1, 0],
           [0, 1]])
Got:
    array([[1, 0],
           [0, 1]], dtype=int8)
```

**Comment by alexwlchan** [comment]
Tests seemed to have passed, just waiting for coveralls. 😕

**Comment by drvinceknight** [comment]
> Tests seemed to have passed, just waiting for coveralls.

I've tried running coverage locally but get:

```
============================================================= 79 passed in 0.35 seconds ==============================================================
Coverage.py warning: No data was collected.
```

(This isn't happening on travis, we're definitely waiting on coveralls there).

**Comment by drvinceknight** [comment]
> (This isn't happening on travis, we're definitely waiting on coveralls there).

DUH! And here's the coverage report from travis:

```
0.18s$ coverage report -m
Name                                                         Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------
src/conference_scheduler/__init__.py                             0      0   100%
src/conference_scheduler/lp_problem/__init__.py                  2      0   100%
src/conference_scheduler/lp_problem/constraints.py              52      0   100%
src/conference_scheduler/lp_problem/objective_functions.py      16      0   100%
src/conference_scheduler/lp_problem/utils.py                    63      0   100%
src/conference_scheduler/resources.py                           64      0   100%
src/conference_scheduler/scheduler.py                           56      0   100%
src/conference_scheduler/validator.py                           25      0   100%
------------------------------------------------------------------------------------------
TOTAL                                                          278      0   100%
```

I think this is good to go!

**Pull request merged**
