### PR TITLE
Set default values for `tags` and `availability`

### LINKED ISSUE #73: Set defaults for `tags` and `unavailability`
In `resources.py` set  `tags=[]` and `unavailability=[]` as defaults. After that we can clear up some of the documentation.

### PR DESCRIPTION
**Pull request by alexwlchan**
Setting default arguments on a namedtuple is moderately fiddly, but this seems to work. Prints in the same way as the original, and has no effect on occupancy:

```pycon
>>> from conference_scheduler.resources import BaseEvent, Event
>>> e = BaseEvent(name='example', duration=60, demand=100, tags=[], unavailability=[])
>>> f = Event(name='example', duration=60, demand=100)
>>> f
Event(name='example', duration=60, demand=100, tags=[], unavailability=[])
>>> assert e.__sizeof__() == f.__sizeof__()
```

Resolves #73.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Looking at some of the code @meatballs before for the resources with defaults it looks like it's a bit simpler than that:

```python
>>> from typing import NamedTuple

>>> class Event(NamedTuple):
...     name: str
...     tags: list = []
        
>>> e = Event("Vince")
>>> e.tags
[]
```

**Comment by drvinceknight** [comment]
```python
>>> e1 = Event("Alex", tags=["web"])
>>> e1.tags
['web']
```

**Comment by alexwlchan** [comment]
Hmm, I get a `TypeError` if I run your `Vince` example. I’m using Python 3.6.0.

I’d also be worried about mutability of the default arguments – what if you modify the `tags` array on an `Event` where it was defaulted?

**Comment by drvinceknight** [comment]
> Hmm, I get a TypeError if I run your Vince example. I’m using Python 3.6.0.
> 
> I’d also be worried about mutability of the default arguments – what if you modify the tags array on an Event where it was defaulted?

It's working fine for me (also py3.6), and it was what was in the `resources.py` file before (for an unused class). 

The imutability is an issue  with using named tuples at all, we deal with that in the documentation by using `extend` and `append`. 

If we go down the line of having a class is there a need to use `NamedTuple` at all?

**Comment by drvinceknight** [comment]
> It's working fine for me (also py3.6)

These new named classes are only in py3.6 I believe?

**Comment by alexwlchan** [comment]
> These new named classes are only in py3.6 I believe?

I think so, yes.

**Comment by drvinceknight** [comment]
I am apparently running `py3.6.1`:

```python
>>> import sys
>>> sys.version
'3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:54:23) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
```

**Comment by alexwlchan** [comment]
> It's working fine for me (also py3.6), and it was what was in the resources.py file before (for an unused class).

Weird. I’m updating to 3.6.1 just in case, although I can’t see anything in the release notes that would suggest this has changed.

> The imutability is an issue with using named tuples at all, we deal with that in the documentation by using extend and append.

Named tuples are weird, because you can cheat the immutability by stuffing in a mutable structure (such as a list). So the following works:

```pycon
>>> my_tuple = ('x', [1, 2, 3], 'y')
>>> my_tuple[1].append(4)
>>> my_tuple
('x', [1, 2, 3, 4], 'y')
```

I have a nasty feeling this will cause stuff to break if you use `[]` as a default argument in a named tuple.

> If we go down the line of having a class is there a need to use NamedTuple at all?

Probably just an occupancy thing, I think.

**Comment by alexwlchan** [comment]
And indeed, your example runs for me on Python 3.6.1.

This is where assigning the arguments in the body of the namedtuple definition breaks down – if you ever modify the default, it’s polluted for new constructions:

```python
from typing import NamedTuple

class Event(NamedTuple):
    name: str
    tags: list = []

e = Event("Vince")
print(e.tags)
e.tags.append('python')

f = Event("Alex")
print(f.tags)
```

**Comment by drvinceknight** [comment]
> Named tuples are weird, because you can cheat the immutability by stuffing in a mutable structure (such as a list). So the following works:

This is what we're doing currently throughout the documentation and I think it's fine. I might be missing something.

> Probably just an occupancy thing, I think.

I don't know what you mean.

**Comment by alexwlchan** [comment]
>> Named tuples are weird, because you can cheat the immutability by stuffing in a mutable structure (such as a list). So the following works:

> This is what we're doing currently throughout the documentation and I think it's fine. I might be missing something.

This is fine if you include `tags=[]` or `unavailability=[]` when you create the named tuple, because you’re explicitly constructing an empty list each time. Each instance of `Event` has its own sandboxed versions of the list – append/extend doesn’t affect what’s going on elsewhere.

If you have a default value of the empty list, all your instances share that default value, and you can cause yourself headaches.

>> Probably just an occupancy thing, I think.

> I don't know what you mean.

The main advantage of named tuples over classes (I think) is that they take up less memory.

**Comment by meatballs** [comment]
> Named tuples are weird, because you can cheat the immutability by stuffing in a mutable structure (such as a list).

That's true of any tuple, not peculiar to named tuples

**Comment by meatballs** [comment]
```
test = (1, [], 3)
print(test[1])

test[1].append(2)
print(test[1])
```

**Comment by drvinceknight** [comment]
> If you have a default value of the empty list, all your instances share that default value, and you can cause yourself headaches.

Ahh! That makes sense. Indeed:

```python
>>> from typing import NamedTuple

>>> class Event(NamedTuple):
...     name: str
...     tags: list = []
        
>>> e = Event("Vince")
>>> e.tags
[]
>>> e1 = Event("Alex")
>>> e1.tags
[]
>>> e.append(4)
>>> e.tags
[4]
>>> eq.tags
[4]
```

Yup: that'll create a mess. :+1:

**Comment by meatballs** [comment]
and using mutable default arguments is a bad idea anywhere - again, not peculiar to named tuples

(and yes, I know I did precisely that in the now abandoned code)

**Comment by drvinceknight** [comment]
> The main advantage of named tuples over classes (I think) is that they take up less memory.

I would suggest going with classes in favour of readability but I'm easy. Whatever is preferred.

**Comment by alexwlchan** [comment]
@meatballs Thanks, good points – I’d gotten firmly stuck down a namedtuple-shaped rabbit hole. 😛

> I would suggest going with classes in favour of readability but I'm easy.

I have no strong preference, it’s your and @meatballs’s codebase. Happy to swap out what I’ve done for a class if you want.

**Comment by meatballs** [comment]
I think the named tuples are more readable. If all we want is a few attributes and we have no need of methods, why bother with the whole `__init__` malarkey?

**Comment by drvinceknight** [comment]
My suggestion was based on the fact that @alexwlchan uses classes anyway to get the default arguments to work (it's making use of the whole `__init__` malarkey): https://github.com/PyconUK/ConferenceScheduler/pull/74/files#diff-b981e2216ee57050ff14dd7c4263fe7eR21

But whatever you prefer.

**Comment by meatballs** [comment]
the default arguments do work - on 3.6.1 There's no need for the structure

**Comment by drvinceknight** [comment]
> the default arguments do work - on 3.6.1 There's no need for the structure

They don't because of the mutability argument:

```python
>>> from typing import NamedTuple

>>> class Event(NamedTuple):
...     name: str
...     tags: list = []
        
>>> e = Event("Vince")
>>> e.tags
[]
>>> e1 = Event("Alex")
>>> e1.tags
[]
>>> e.append(4)
>>> e.tags
[4]
>>> e1.tags
[4]
```

That will create all sorts of problems.

**Comment by meatballs** [comment]
that's a different point - using mutable default arguments is a bad idea whether we're talking about named tuples, classes, functions or anything else

**Comment by drvinceknight** [comment]
> That will create all sorts of problems.

We need to be able to append to `unavailability` for example because of the fact that we might need to create all events before appending one event to another event's `unavailability`.

**Comment by meatballs** [comment]
so the default argument in that example should be `None` rather than `[]`

**Comment by drvinceknight** [comment]
> so the default argument in that example should be None rather than []

Ok that'll need us to be careful with the constraints etc...


```python
>>> for f in None:
>>>     print(f)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-cc65c754fad2> in <module>()
----> 1 for f in None:
      2     print(f)

TypeError: 'NoneType' object is not iterable
```

**Comment by drvinceknight** [comment]
(Not insurmountable with a `if event.tags is not None`)

**Comment by meatballs** [comment]
> so the default argument in that example should be None rather than []

However, I accept that, if we used an ordinary class, we could set the attribute to be `[]` if the argument passed was `None`

**Comment by meatballs** [comment]
> (Not insurmountable with a if event.tags is not None)

or event just `if event.tags`

**Comment by drvinceknight** [comment]
> or event just if event.tags

Here be gremlins! I don't recommend this, it can be confused when `event.tags=False` or `events.tags=0` etc...

Note if we go down this route, we should probably push https://github.com/PyconUK/ConferenceScheduler/blob/master/setup.py#L18 to 3.6.1.

**Comment by drvinceknight** [comment]
I do wonder if it would just be simpler to use a `class`...

**Comment by meatballs** [comment]
To summarise, I think we have two options:

```
class Event(NamedTuple):
    name: str
    tags: list = None
```
which means using some conditions in our constraints and passing `[]` when we know we need to append to tags, or, 

```
class Event(object):

    def __init__(self, name, tags=None):
        self.name = name
        if tags is None:
            self.tags = []
        else:
            self.tags = tags
````

**Comment by meatballs** [comment]
I stick by the named tuple being more concise and therefore, for me, more readable. I would use them wherever anything else is unnecessary.

However, here, I think there's a good argument for the class since we know we want an empty list to start with but we'll be appending to it later.

**Comment by drvinceknight** [comment]
My vote would be for the second approach, we might want to add a `__repr__` to it though as it would break our doctests. Another option of course is what @alexwlchan has which I think is what makes the least modification to the current code base.

Personally I'd prefer one of two options listed by @meatballs in favour of clarity.

**Comment by drvinceknight** [comment]
> However, here, I think there's a good argument for the class since we know we want an empty list to start with but we'll be appending to it later.

:+1:

**Comment by drvinceknight** [comment]
Your call @meatballs. Whatever you prefer.

**Comment by meatballs** [comment]
In this instance, let's go for the class

Elsewhere, if there are default arguments which aren't mutable, we stick with a Named Tuple.

**Comment by alexwlchan** [comment]
Okay, class-based implementation pushed.

**Comment by drvinceknight** [comment]
Looks good to me.

**Comment by drvinceknight** [comment]
> Add a changelog entry

Show off... Now I'm going to need to start doing that :) :+1: :laughing:

**Comment by meatballs** [comment]
Nice job! Thanks @alexwlchan

**Pull request merged**
