### PR TITLE
Remove things that are not being used.

### PR DESCRIPTION
**Pull request by drvinceknight**
I'm not sure if this is useful or not. There two things confused me for
a little while. I'm pretty sure they're perhaps legacy code or
redundant. When I deleted them, it broke no tests so deleting them here
but please feel free to close this PR if I'm missing something and they
have a purpose.

### CODE REVIEW

**Comment by meatballs** [comment]
That's the function that wraps the output 'raw' solution into a list of ScheduledItems. It's what I envisage as the final output

**Comment by drvinceknight** [comment]
> That's the function that wraps the output 'raw' solution into a list of ScheduledItems. It's what I envisage as the final output

Cool.

**Comment by drvinceknight** [comment]
> That's the function that wraps the output 'raw' solution into a list of ScheduledItems.

Actually: is that not what `_solution_to_schedule` is for?

**Comment by drvinceknight** [comment]
(That function **is** tested.)

**Comment by meatballs** [comment]
Unfortunately, we have two forms of 'solution' at the moment. What comes out of the `solution` function is not the same as the numpy arrays we're now referring to as solutions

**Pull request closed without merging**
