### PR TITLE
Switch to using an src/ directory in the repo root

### PR DESCRIPTION
**Pull request by alexwlchan**
Picking up @drvinceknight’s suggestion from #52.

### CODE REVIEW

**Comment by alexwlchan** [comment]
(Largely cribbed from the Hypothesis repo.)

**Comment by meatballs** [comment]
I now cannot run the test suite at all. tox doesn't play nicely with my environment and running pytest is giving me import errors

**Comment by meatballs** [comment]
Could we perhaps split this up? The original suggestion was purely to move to a structure based on `src` so let's have a PR for that and then, separately, we can look at tox if we think that's worthwhile.

For me, I'm not wholly convinced of the value of tox. I've never been able to get it to work reliably on my local system and I'm not keen on the effort of making another attempt now.

**Comment by alexwlchan** [comment]
> Could we perhaps split this up? The original suggestion was purely to move to a structure based on src so let's have a PR for that and then, separately, we can look at tox if we think that's worthwhile.

Sure, I’ll push that now.

(I have no strong opinions on tox, I was trying to get the tests to pass with the `src`-based structure. In my sleep-addled state, I entirely forgot that, uh, you could just do `python setup.py install`. 😛 )

**Comment by drvinceknight** [comment]
> I'm not wholly convinced of the value of tox.

I've never gotten along with tox myself.

**Comment by meatballs** [comment]
@alexwlchan do you want me to take a look at this or are you still working on it?

**Comment by alexwlchan** [comment]
@meatballs I was planning to dig into the coverage issue later this afternoon.

**Comment by meatballs** [comment]
@alexwlchan You ok for me to close this?

**Comment by drvinceknight** [comment]
I'm closing this, please reopen if that's a mistake.

**Pull request closed without merging**
