### PR TITLE
Fix bugs with datetime objects and strings

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Is the bug here that we were writing them as date time objects but the way we do this is to only take strings as inputs? (Just checking I understand :))

**Comment by meatballs** [comment]
Yep. That was exactly the problem. If you pass the events and slots lists from the howto into the scheduler, it all falls over!

**Comment by meatballs** [comment]
I may have a look at doing that datetime stuff in a smarter fashion but at least for now, it's correct!

**Comment by drvinceknight** [comment]
> I may have a look at doing that datetime stuff in a smarter fashion but at least for now, it's correct!

Instead of a string we could take a `datetime` as input (so the way you had it here would be correct)? That makes things simpler on the library's side? The user just needs to create the datetime objects?

**Comment by meatballs** [comment]
I think so, but part of me was reluctant to go to version 3.0.0 just for that. silly really

**Pull request merged**
