### PR TITLE
Add solver and kwargs arguments to scheduler.array

### LINKED ISSUE #90: Pass solver and kwargs to scheduler.array
We are missing the `solver` and `kwargs` parameters in the `scheduler.array` function.

Both the `solution` and `schedule` functions have those arguments but, if we want to compute the array form using an external solver, we have to use one of the conversion functions.

### PR DESCRIPTION
**Pull request by meatballs**
Fixes #90

### CODE REVIEW

**Comment by drvinceknight** [comment]
Looks fine to me, do we want to add a test?

**Comment by meatballs** [comment]
I decided against it - we don't have tests for the equivalent existing arguments on the other functions and it would be difficult to test.

We'd probably end up using mocks and I'm not wholly convinced of the value then.

**Comment by drvinceknight** [comment]
> we don't have tests for the equivalent existing arguments on the other functions

Fine by me but just FYI: https://github.com/PyconUK/ConferenceScheduler/blob/master/tests/test_scheduler.py#L89

**Comment by meatballs** [comment]
Oh! Missed that one

**Comment by meatballs** [comment]
OK, I'll add something similar

**Comment by drvinceknight** [comment]
I'm merging (coverage is fine).

**Pull request merged**
